import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";
import DropDownNav from "@/components/shared/DropDownNav";
import { CartProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dokani Bhai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="max-w-screen-2xl mx-auto">
        <CartProvider>
          <div className="mb-[71px]">
          <NavBar></NavBar> 
          </div>

        <DropDownNav></DropDownNav>
        {children}
        <Footer></Footer> 
        </CartProvider>
        </div>
        
        </body>
    </html>
  );
}


// import { Inter } from "next/font/google";
// import "./globals.css";

// import { Roboto } from 'next/font/google'
 
// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
// })

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Dokani Bhai",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={roboto.className}>{children}</body>
//     </html>
//   );
// }
